theme              : jekyll-theme-minimal
title              : Classroom Resources Manager
description        : >-
                    This website is a resource for Practical and Reproducible Data Science 

url                : https://smcnew.github.io/ECOL_600_datascience/
baseurl            : /ECOL_600_datascience

# SEO tag
twitter:
  username         : sabrinamcnew

author:
  name             : Sabrina McNew
  email            : mcnew@arizona.edu

social:
  name             : Sabrina McNew
  links:
                   - https://twitter.com/sabrinamcnew
                   - https://sabrinamcnew.com
                   - https://github.com/smcnew

plugins:
  - jekyll-seo-tag

# Build settings
highlighter        : rouge
markdown           : kramdown
lsi                : false

collections:
  courses:
    output        : true
    permalink     : /:collection/:title 
  resources:
    output        : true
    permalink     : /:collection/:title

defaults:
  - scope:
      path         : ""
      type         : courses
    values:
      layout       : course
  - scope:
      path         : ""
      type         : resources
    values:
      type         : pdf
      date         : 2017-12-01 00:00:00
      layout       : resource

include:
                   - _pages

exclude: 
                   - LICENSE
                   - README.md
                   - CNAME
                   - .gitignore
                   - Gemfile
                   - Gemfile.lock
                   - .jekyll-metadata

